/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as HiddenPlacesRouteImport } from './routes/hidden-places'
import { Route as MindfulEscapesRouteImport } from './routes/mindful-escapes'
import { Route as MyVoyayahaRouteImport } from './routes/my-voyayaha'
import { Route as SpiritualJourneysRouteImport } from './routes/spiritual-journeys'
import { Route as VillageLocalRouteImport } from './routes/village-local'
import { Route as PlacesSlugRouteImport } from './routes/places.$slug'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'
import { Route as ApiTravelIntelRouteImport } from './routes/api/travel-intel'
import { Route as ApiVillageExperiencesRouteImport } from './routes/api/village-experiences'
import { Route as ApiTravelMemoriesRouteImport } from './routes/api/travel-memories'
import { Route as ApiTravelMemoryRouteImport } from './routes/api/travel-memory'
import { Route as ApiSocialDiscoveryRouteImport } from './routes/api/social-discovery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenPlacesRoute = HiddenPlacesRouteImport.update({
  id: '/hidden-places',
  path: '/hidden-places',
  getParentRoute: () => rootRouteImport,
} as any)
const MindfulEscapesRoute = MindfulEscapesRouteImport.update({
  id: '/mindful-escapes',
  path: '/mindful-escapes',
  getParentRoute: () => rootRouteImport,
} as any)
const MyVoyayahaRoute = MyVoyayahaRouteImport.update({
  id: '/my-voyayaha',
  path: '/my-voyayaha',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiritualJourneysRoute = SpiritualJourneysRouteImport.update({
  id: '/spiritual-journeys',
  path: '/spiritual-journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const VillageLocalRoute = VillageLocalRouteImport.update({
  id: '/village-local',
  path: '/village-local',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelIntelRoute = ApiTravelIntelRouteImport.update({
  id: '/api/travel-intel',
  path: '/api/travel-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVillageExperiencesRoute = ApiVillageExperiencesRouteImport.update({
  id: '/api/village-experiences',
  path: '/api/village-experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelMemoriesRoute = ApiTravelMemoriesRouteImport.update({
  id: '/api/travel-memories',
  path: '/api/travel-memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelMemoryRoute = ApiTravelMemoryRouteImport.update({
  id: '/api/travel-memory',
  path: '/api/travel-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialDiscoveryRoute = ApiSocialDiscoveryRouteImport.update({
  id: '/api/social-discovery',
  path: '/api/social-discovery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/heritage': typeof HeritageRoute
  '/hidden-places': typeof HiddenPlacesRoute
  '/mindful-escapes': typeof MindfulEscapesRoute
  '/my-voyayaha': typeof MyVoyayahaRoute
  '/spiritual-journeys': typeof SpiritualJourneysRoute
  '/village-local': typeof VillageLocalRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/api/travel-intel': typeof ApiTravelIntelRoute
  '/api/village-experiences': typeof ApiVillageExperiencesRoute
  '/api/travel-memories': typeof ApiTravelMemoriesRoute
  '/api/travel-memory': typeof ApiTravelMemoryRoute
  '/api/social-discovery': typeof ApiSocialDiscoveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/heritage': typeof HeritageRoute
  '/hidden-places': typeof HiddenPlacesRoute
  '/mindful-escapes': typeof MindfulEscapesRoute
  '/my-voyayaha': typeof MyVoyayahaRoute
  '/spiritual-journeys': typeof SpiritualJourneysRoute
  '/village-local': typeof VillageLocalRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/api/travel-intel': typeof ApiTravelIntelRoute
  '/api/village-experiences': typeof ApiVillageExperiencesRoute
  '/api/travel-memories': typeof ApiTravelMemoriesRoute
  '/api/travel-memory': typeof ApiTravelMemoryRoute
  '/api/social-discovery': typeof ApiSocialDiscoveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/heritage': typeof HeritageRoute
  '/hidden-places': typeof HiddenPlacesRoute
  '/mindful-escapes': typeof MindfulEscapesRoute
  '/my-voyayaha': typeof MyVoyayahaRoute
  '/spiritual-journeys': typeof SpiritualJourneysRoute
  '/village-local': typeof VillageLocalRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/api/travel-intel': typeof ApiTravelIntelRoute
  '/api/village-experiences': typeof ApiVillageExperiencesRoute
  '/api/travel-memories': typeof ApiTravelMemoriesRoute
  '/api/travel-memory': typeof ApiTravelMemoryRoute
  '/api/social-discovery': typeof ApiSocialDiscoveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/heritage'
    | '/hidden-places'
    | '/mindful-escapes'
    | '/my-voyayaha'
    | '/spiritual-journeys'
    | '/village-local'
    | '/places/$slug'
    | '/api/public/sitemap'
    | '/api/travel-intel'
    | '/api/village-experiences'
    | '/api/travel-memories'
    | '/api/travel-memory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/heritage'
    | '/hidden-places'
    | '/mindful-escapes'
    | '/my-voyayaha'
    | '/spiritual-journeys'
    | '/village-local'
    | '/places/$slug'
    | '/api/public/sitemap'
    | '/api/travel-intel'
    | '/api/village-experiences'
    | '/api/travel-memories'
    | '/api/travel-memory'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/heritage'
    | '/hidden-places'
    | '/mindful-escapes'
    | '/my-voyayaha'
    | '/spiritual-journeys'
    | '/village-local'
    | '/places/$slug'
    | '/api/public/sitemap'
    | '/api/travel-intel'
    | '/api/village-experiences'
    | '/api/travel-memories'
    | '/api/travel-memory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  HeritageRoute: typeof HeritageRoute
  HiddenPlacesRoute: typeof HiddenPlacesRoute
  MindfulEscapesRoute: typeof MindfulEscapesRoute
  MyVoyayahaRoute: typeof MyVoyayahaRoute
  SpiritualJourneysRoute: typeof SpiritualJourneysRoute
  VillageLocalRoute: typeof VillageLocalRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
  ApiTravelIntelRoute: typeof ApiTravelIntelRoute
  ApiVillageExperiencesRoute: typeof ApiVillageExperiencesRoute
  ApiTravelMemoriesRoute: typeof ApiTravelMemoriesRoute
  ApiTravelMemoryRoute: typeof ApiTravelMemoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-places': {
      id: '/hidden-places'
      path: '/hidden-places'
      fullPath: '/hidden-places'
      preLoaderRoute: typeof HiddenPlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindful-escapes': {
      id: '/mindful-escapes'
      path: '/mindful-escapes'
      fullPath: '/mindful-escapes'
      preLoaderRoute: typeof MindfulEscapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-voyayaha': {
      id: '/my-voyayaha'
      path: '/my-voyayaha'
      fullPath: '/my-voyayaha'
      preLoaderRoute: typeof MyVoyayahaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spiritual-journeys': {
      id: '/spiritual-journeys'
      path: '/spiritual-journeys'
      fullPath: '/spiritual-journeys'
      preLoaderRoute: typeof SpiritualJourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/village-local': {
      id: '/village-local'
      path: '/village-local'
      fullPath: '/village-local'
      preLoaderRoute: typeof VillageLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel-intel': {
      id: '/api/travel-intel'
      path: '/api/travel-intel'
      fullPath: '/api/travel-intel'
      preLoaderRoute: typeof ApiTravelIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/village-experiences': {
      id: '/api/village-experiences'
      path: '/api/village-experiences'
      fullPath: '/api/village-experiences'
      preLoaderRoute: typeof ApiVillageExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel-memories': {
      id: '/api/travel-memories'
      path: '/api/travel-memories'
      fullPath: '/api/travel-memories'
      preLoaderRoute: typeof ApiTravelMemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel-memory': {
      id: '/api/travel-memory'
      path: '/api/travel-memory'
      fullPath: '/api/travel-memory'
      preLoaderRoute: typeof ApiTravelMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  HeritageRoute: HeritageRoute,
  HiddenPlacesRoute: HiddenPlacesRoute,
  MindfulEscapesRoute: MindfulEscapesRoute,
  MyVoyayahaRoute: MyVoyayahaRoute,
  SpiritualJourneysRoute: SpiritualJourneysRoute,
  VillageLocalRoute: VillageLocalRoute,
  PlacesSlugRoute: PlacesSlugRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
  ApiTravelIntelRoute: ApiTravelIntelRoute,
  ApiVillageExperiencesRoute: ApiVillageExperiencesRoute,
  ApiTravelMemoriesRoute: ApiTravelMemoriesRoute,
  ApiTravelMemoryRoute: ApiTravelMemoryRoute,
  ApiSocialDiscoveryRoute: ApiSocialDiscoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
